### ISSUE TITLE
Esp 07 led blinking and no "RC" network created

### ISSUE THREAD

**Issue by JBJUANBA** [emente/evalink#1]
I have uploaded the TX code to an Esp 07  (after choosing the correct settings in Arduino), and the blue led doesn't stop blinking (no ppm input at first) and there is no RC network in wifi stations.

I uploaded both tx and rx code to an Esp-01 and they work nice, and I checked the network called "RC". What I don't know is if the rc wifi network is stablished when tx and rx are paired.

thanks

**Comment by RobertHubar** [comment]
hello, I uploaded your code to ESP8266, the LED is flashing and nothing happens, could you describe the TX&RX settings in more detail?

**Comment by emente** [comment]
> What I don't know is if the rc wifi network is stablished when tx and rx are paired.

As the documentation states:
> PPM is transported using raw packets (no wifi peering or binding needed)

As the code states:
> no wifi peering/bind needed, we are are using raw beacon packets

**Comment by emente** [comment]
> hello, I uploaded your code to ESP8266, the LED is flashing and nothing happens, could you describe the TX&RX settings in more detail?

"I just uploaded it without taking a look at the code and it does not work. Whats wrong?"
RTFM
